### ISSUE TITLE
I have a few questions with track-address

### ISSUE THREAD

**Issue by Victor1890** [mempool/mempool.js#104]
Hello there! Right now, I'm working with MempoolJS and I have a few questions related to track-address.

When I subscribe one address and I make a payment to it, I'm receiving one property called **address-transactions**, in this step all is correct, but when I restart the server, the **address-transactions** doesn't show anything else, and I want to ask you guys, is it possible to subscribe one address for more time???

That is a little example code about how to implement that **track-address** event

```js
const ws = new WebSocket("wss://mempool.space/api/v1/ws");

ws.on('open', () => {
     ws.send(JSON.stringify({ 'track-address': "btc address"}));
});
```

**Comment by mononaut** [comment]
>when I restart the server

what do you mean, exactly?

**Comment by Victor1890** [comment]
Hello @mononaut 

I'm subscribing an address, I'm sending BTC to it and I'm receiving the transaction event correctly, but when the ws connection get closed for some reason, i.g. when I retart the node.js server, I'm subscribing that address again, sending another transaction and the event never come. That's my issue, I need to be able to subscribe the address again.
