### ISSUE TITLE
const liquid = liquidJS( bc1qjwz55y5a24nusxutnhykq08scxxedvh9wpu7q6  );

### ISSUE THREAD

**Issue by Khorshidgardan** [mempool/mempool.js#163]
### Discussed in https://github.com/mempool/mempool.js/discussions/162

<div type='discussions-op-text'>

<sup>Originally posted by **Khorshidgardan** February  8, 2024</sup>
bc1qjwz55y5a24nusxutnhykq08scxxedvh9wpu7q6</div>

**Comment by Chu2023js** [comment]
I need help
