### ISSUE TITLE
Just in case there's any significance to it, here's a sample of the log when I looked just now. It still shows 'Offline' when viewing the mempool page.

### ISSUE THREAD

**Issue by Cryptocurrencei** [mempool/mempool.js#178]
Just in case there's any significance to it, here's a sample of the log when I looked just now. It still shows 'Offline' when viewing the mempool page.

-- Logs begin at Fri 2020-10-30 14:01:54 CDT, end at Fri 2020-10-30 14:39:56 CDT. --
Oct 30 14:39:53 mynode mempoolspace[26332]: Fetching block tx 630 of 2884
Oct 30 14:39:52 mynode mempoolspace[26332]: Fetching block tx 629 of 2884
Oct 30 14:39:51 mynode mempoolspace[26332]: Fetching block tx 628 of 2884
Oct 30 14:39:48 mynode mempoolspace[26332]: Fetching block tx 627 of 2884
Oct 30 14:39:47 mynode mempoolspace[26332]: Fetching block tx 626 of 2884
Oct 30 14:39:46 mynode mempoolspace[26332]: Fetching block tx 625 of 2884
Oct 30 14:39:45 mynode mempoolspace[26332]: Fetching block tx 624 of 2884
Oct 30 14:39:45 mynode mempoolspace[26332]: Fetching block tx 623 of 2884
Oct 30 14:39:43 mynode mempoolspace[26332]: Fetching block tx 622 of 2884
Oct 30 14:39:30 mynode mempoolspace[26332]: Fetching block tx 621 of 2884
Oct 30 14:39:02 mynode mempoolspace[26332]: Statistics cache created
Oct 30 14:39:00 mynode mempoolspace[26332]: Fetching block tx 620 of 2884
Oct 30 14:38:57 mynode mempoolspace[26332]: Fetching block tx 619 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 618 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 617 of 2884
Oct 30 14:38:56 mynode mempoolspace[26332]: Fetching block tx 616 of 2884
Oct 30 14:38:54 mynode mempoolspace[26332]: Fetching block tx 615 of 2884
Oct 30 14:38:48 mynode mempoolspace[26332]: Fetching block tx 614 of 2884
Oct 30 14:38:43 mynode mempoolspace[26332]: Fetching block tx 613 of 2884
Oct 30 14:38:40 mynode mempoolspace[26332]: Fetching block tx 612 of 2884
Oct 30 14:38:36 mynode mempoolspace[26332]: Fetching block tx 611 of 2884
Oct 30 14:38:33 mynode mempoolspace[26332]: Fetching block tx 610 of 2884
Oct 30 14:38:33 mynode mempoolspace[26332]: Fetching block tx 609 of 2884
Oct 30 14:38:31 mynode mempoolspace[26332]: Fetching block tx 608 of 2884
Oct 30 14:38:29 mynode mempoolspace[26332]: Fetching block tx 607 of 2884
Oct 30 14:38:25 mynode mempoolspace[26332]: Fetching block tx 606 of 2884
Oct 30 14:38:18 mynode mempoolspace[26332]: Fetching block tx 605 of 2884
Oct 30 14:38:15 mynode mempoolspace[26332]: Fetching block tx 604 of 2884
Oct 30 14:38:10 mynode mempoolspace[26332]: Fetching block tx 603 of 2884
Oct 30 14:37:51 mynode mempoolspace[26332]: Fetching block tx 602 of 2884
Oct 30 14:37:48 mynode mempoolspace[26332]: Fetching block tx 601 of 2884
Oct 30 14:37:47 mynode mempoolspace[26332]: Fetching block tx 600 of 2884
Oct 30 14:37:46 mynode mempoolspace[26332]: Fetching block tx 599 of 2884
Oct 30 14:37:46 mynode mempoolspace[26332]: Fetching block tx 598 of 2884
Oct 30 14:37:42 mynode mempoolspace[26332]: Fetching block tx 597 of 2884
Oct 30 14:37:41 mynode mempoolspace[26332]: Fetching block tx 596 of 2884
Oct 30 14:37:36 mynode mempoolspace[26332]: Fetching block tx 595 of 2884
Oct 30 14:37:32 mynode mempoolspace[26332]: Fetching block tx 594 of 2884

The difference from the first log is: there is none of this (below) in the log this time:

}
Oct 29 15:38:29 mynode mempoolspace[31003]: code: -32602
Oct 29 15:38:29 mynode mempoolspace[31003]: at processTicksAndRejections (internal/process/task_queues.js:81:21) {
Oct 29 15:38:29 mynode mempoolspace[31003]: at endReadableNT (_stream_readable.js:1185:12)
Oct 29 15:38:29 mynode mempoolspace[31003]: at IncomingMessage.emit (events.js:228:7)
Oct 29 15:38:29 mynode mempoolspace[31003]: at IncomingMessage. (/mempool.space/backend/node_modules/bitcoin/lib/jsonrpc.js:110:17)
Oct 29 15:38:29 mynode mempoolspace[31003]: Error getMempoolInfo Error: Invalid params, response status code: 500
Oct 29 15:38:29 mynode mempoolspace[31003]: }

_Originally posted by @calligrl in https://github.com/mynodebtc/mynode/issues/431#issuecomment-719765269_

**Comment by softsimon** [comment]
This is not related to the mempool.JS repo.
