### ISSUE TITLE
New difficulty endpoint is returning 404

### ISSUE THREAD

**Issue by mbombonato** [mempool/mempool.js#28]
mempool.js is not using the correct path for the new endpoint.

Wrong: https://mempool.space/api/difficulty-adjustment
Correct: https://mempool.space/api/v1/difficulty-adjustment

Is this a new path for new endpoints? All the old endpoints are not using **v1/**

**Comment by wiz** [comment]
@knorrium it looks like @MiguelMedeiros could use some test cases for the JS library

**Comment by MiguelMedeiros** [comment]
> mempool.js is not using the correct path for the new endpoint.
> 
> Wrong: https://mempool.space/api/difficulty-adjustment
> Correct: https://mempool.space/api/v1/difficulty-adjustment
> 
> Is this a new path for new endpoints? All the old endpoints are not using **v1/**

Thanks for reporting!
Fixed with v2.2.4 patch!

Please upgrade your npm package! :)
