### ISSUE TITLE
Feature request for difficulty adjustment endpoint

### ISSUE THREAD

**Issue by mbombonato** [mempool/mempool.js#29]
Its would be nice if we could have the current "Difficulty (14.50 T)" and the network "Hash Rate (117.461,40 TH/s)" (maybe last 24h is enough)

Thanks :)

**Comment by MiguelMedeiros** [comment]
Thanks for reporting! 
Fixed with v2.2.4 patch!

Please upgrade your npm package! :)

**Comment by joegraser** [comment]
I want my money I did what I was supposed  to now it say block chain

**Comment by CryptStephy** [comment]
Same for me 🤨😮‍💨

- I have all the documents and receipts] from my bank account and my e-wallet.
Please 🙏 🙏 🙏  help me please 🙏 😢
