### ISSUE TITLE
Correct custom hostname, port and ssl setting

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool.js#42]
Make sure that mempool.js is configurable with custom hostname, port and HTTP/HTTPS and WS/WSS.

* mempool.js defaults to HTTPS, it only switches to HTTP if the hostname contains the word 'localhost'
* umbrel.local requires port 3006 to be specified (you can fake this by entering hostname 'umbrel@local:3006', but the umbrel example omits this
* once these two issue are overcome, mempool.js is hardcoded to WSS, so even if type hostname 'umbrel.local:3006' the connection is over WSS, and needs to be WS

**Comment by Classof08615** [comment]
Correspondence dept. motion sensor monitor system reg system complete

**Comment by 123ENR93** [comment]
> Asegúrese de que mempool.js se pueda configurar con un nombre de host personalizado, puerto y HTTP/HTTPS y WS/WSS.
> 
> * mempool.js por defecto es HTTPS, solo cambia a HTTP si el nombre de host contiene la palabra 'localhost'
> * umbrel.local requiere que se especifique el puerto 3006 (puede falsificar esto ingresando el nombre de host 'umbrel@local:3006', pero el ejemplo de umbrel omite esto
> * una vez que se superan estos dos problemas, mempool.js está codificado en WSS, por lo que incluso si escribe el nombre de host 'umbrel.local: 3006', la conexión es a través de WSS y debe ser WS

**Comment by brunoAmado** [comment]
> Make sure that mempool.js is configurable with custom hostname, port and HTTP/HTTPS and WS/WSS.
> 
>     * mempool.js defaults to HTTPS, it only switches to HTTP if the hostname contains the word 'localhost'
> 
>     * umbrel.local requires port 3006 to be specified (you can fake this by entering hostname 'umbrel@local:3006', but the umbrel example omits this
> 
>     * once these two issue are overcome, mempool.js is hardcoded to WSS, so even if type hostname 'umbrel.local:3006' the connection is over WSS, and needs to be WS

+1

**Comment by RaySwag522** [comment]
Verify

**Comment by softsimon** [comment]
Solved with https://github.com/mempool/mempool.js/pull/174
