### ISSUE TITLE
Can't use mempool.js to broadcast raw transaction to signet.

### ISSUE THREAD

**Issue by Bzvwf16WSDKoSZd8** [mempool/mempool.js#59]
I installed the lastest version of mempool.js from npm.
https://www.npmjs.com/package/@mempool/mempool.js

Node.js version is v18.5.0

My code is....
```ts
import mempoolJS from '@mempool/mempool.js'

const { bitcoin: { transactions } } = mempoolJS({
    hostname: 'mempool.space',
    network: 'signet'
})

const txhex = 'a_valid_txhex';
const txid = await transactions.postTx({ txhex });

console.log(txid);
```
Run the program, then throwing this exception.
'sendrawtransaction RPC error: {"code":-22,"message":"TX decode failed. Make sure the tx has at least one input."}'

I copied the same txhex to https://mempool.space/signet/tx/push
The transaction is broadcast successfully!

This obviously is a bug from mempool.js

**Comment by Bzvwf16WSDKoSZd8** [comment]
Due to no response, moved to here.
[https://github.com/mempool/mempool/issues/2165](url)

**Comment by bucko13** [comment]
Did you manage to get this to work? I'm running into the same thing (only tested on testnet so far)

**Comment by testnetprotonmail** [comment]
> Did you manage to get this to work? I'm running into the same thing (only tested on testnet so far)

same error on testnet

**Comment by testnetprotonmail** [comment]
I solved it by changing 
```
                    case 0: return [4 /*yield*/, api.post("/tx", { txhex: params.txhex })];
```
to

```                    case 0: return [4 /*yield*/, api.post("/tx", params.txhex)];
``` 

should be an easy hotfix

**Comment by testnetprotonmail** [comment]
https://github.com/mempool/mempool.js/pull/84
