### ISSUE TITLE
https://mempool.space/api/blocks/tip/hash

### ISSUE THREAD

**Issue by 1710199225101962** [mempool/mempool.js#71]

**Comment by Ibrahim7388** [comment]
[{   btc_usd: {     buys: [       {         offer_id: "ORHL1BE-0c193d04-be60-4657-ba42-cc172bb4ae5d-172",         offer_date: 1630207815462,         direction: "BUY",         min_amount: "0.00500000",         amount: "0.01500000",         price: "50030.24770000",         volume: "750.45370000",         payment_method: "AMAZON_GIFT_CARD",         offer_fee_txid: null         },         ...     ],     sells: [       {         offer_id: "nswiwkre-7676d5e6-e808-4c47-9c51-d5708e465ad5-172",         offer_date: 1630320354509,         direction: "SELL",         min_amount: "0.04170000",         amount: "0.04170000",         price: "49534.89880000",         volume: "2065.60520000",         payment_method: "CASH_DEPOSIT",         offer_fee_txid: null         },         ...     ]   } }]({   btc_usd: {     buys: [       {         offer_id: "ORHL1BE-0c193d04-be60-4657-ba42-cc172bb4ae5d-172",         offer_date: 1630207815462,         direction: "BUY",         min_amount: "0.00500000",         amount: "0.01500000",         price: "50030.24770000",         volume: "750.45370000",         payment_method: "AMAZON_GIFT_CARD",         offer_fee_txid: null         },         ...     ],     sells: [       {         offer_id: "nswiwkre-7676d5e6-e808-4c47-9c51-d5708e465ad5-172",         offer_date: 1630320354509,         direction: "SELL",         min_amount: "0.04170000",         amount: "0.04170000",         price: "49534.89880000",         volume: "2065.60520000",         payment_method: "CASH_DEPOSIT",         offer_fee_txid: null         },         ...     ]   } }) #72

**Comment by 1710199225101962** [comment]
Можно на русском? Или на казахском

чт, 26 янв. 2023 г., 21:49 Ibrahim7388 ***@***.***>:
