### ISSUE TITLE
how to subscribe to a specific address to see transactions with websocket with nodejs?

### ISSUE THREAD

**Issue by calboru** [mempool/mempool.js#91]
Documentation on the website is not clear, where do we pass the track-address parameter as stated on the documentation?

{ 'track-address': '3PbJ...bF9B' } ===> how do we pass this param to see the transaction for a specific address?

  const ws = websocket.initServer({
    options: ["blocks", "stats", "mempool-blocks", "live-2h-chart"],
  });

**Comment by Sammiegirl411** [comment]
My blockchain bitcoin address is
31qtDhLPp8bRwek2wPyKg6FHAXXQdsLZV5


Samantha Henson

**Comment by Sammiegirl411** [comment]
I just want to know where my money is n how can I access it??

Samantha Henson

**Comment by BeycanDeveloper** [comment]
Yeah i have same problem too

**Comment by Victor1890** [comment]
I have the same problem, I'm trying to implement "track-address", but I don't know how to do it 🥲
